version: 2
root-markers:
  - .git/
lint-debounce: 1s

commands:
  - command: code
    arguments:
      - ${INPUT}

tools:
  black: &black
    format-command: 'black --quiet -'
    format-stdin: true
  shfmt: &shfmt
    format-command: 'shfmt -'
    format-stdin: true

languages:
  python:
    - <<: *black
  sh:
    - <<: *shfmt


