[".local/share/oh-my-tmux"]
type = "git-repo"
url = "https://github.com/gpakosz/.tmux"
refreshPeriod = "24h"

[".goenv"]
type = "git-repo"
url = "https://github.com/syndbg/goenv"
refreshPeriod = "24h"

[".pyenv"]
type = "git-repo"
url = "https://github.com/pyenv/pyenv"
refreshPeriod = "24h"

[".local/share/nautilus-python/extensions/code-nautilus.py"]
type = "file"
url = "https://raw.githubusercontent.com/harry-cpp/code-nautilus/master/code-nautilus.py"
refreshPeriod = "5m"

[".local/share/fcitx5/rime"]
type = "git-repo"
url = "https://github.com/black-desk/rime-ice"
refreshPeriod = "24h"

[".local/share/nvim/rime-ls"]
type = "git-repo"
url = "https://github.com/black-desk/rime-ice"
refreshPeriod = "24h"

[".ssh/config.d/aosc"]
type = "file"
url = "https://cdn.jsdelivr.net/gh/AOSC-Dev/Buildbots/ssh_config"
refreshPeriod = "24h"

[".ssh/known_hosts.d/aosc"]
type = "file"
url = "https://cdn.jsdelivr.net/gh/AOSC-Dev/Buildbots/ssh_known_hosts"
refreshPeriod = "24h"

[".local/bin/pandocx"]
type = "file"
url = "https://raw.githubusercontent.com/black-desk/PandocX/refs/heads/master/pandocx"
refreshPeriod = "24h"
executable = true
