# tmux config
[".tmux.conf"]
        type = "file"
        url = "https://raw.githubusercontent.com/gpakosz/.tmux/master/.tmux.conf"
        refreshPeriod = "24h"
# goenv
[".goenv"]
        type = "git-repo"
        url = "https://github.com/syndbg/goenv"
# pyenv
[".pyenv"]
        type = "git-repo"
        url = "https://github.com/pyenv/pyenv"
