[".tmux.conf"]
type = "file"
url = "https://raw.githubusercontent.com/gpakosz/.tmux/master/.tmux.conf"
refreshPeriod = "24h"

[".goenv"]
type = "git-repo"
url = "https://github.com/syndbg/goenv"

[".pyenv"]
type = "git-repo"
url = "https://github.com/pyenv/pyenv"

[".local/bin/mdoc"]
type = "file"
url = "https://github.com/black-desk/mdoc/releases/latest/download/mdoc"
executable = true
refreshPeriod = "5m"

[".local/share/nautilus-python/extensions/code-nautilus.py"]
type = "file"
url = "https://raw.githubusercontent.com/harry-cpp/code-nautilus/master/code-nautilus.py"
refreshPeriod = "5m"
