[".local/share/oh-my-tmux"]
type = "git-repo"
url = "https://github.com/gpakosz/.tmux"
refreshPeriod = "24h"

[".goenv"]
type = "git-repo"
url = "https://github.com/syndbg/goenv"

[".pyenv"]
type = "git-repo"
url = "https://github.com/pyenv/pyenv"

[".local/share/nautilus-python/extensions/code-nautilus.py"]
type = "file"
url = "https://raw.githubusercontent.com/harry-cpp/code-nautilus/master/code-nautilus.py"
refreshPeriod = "5m"

[".local/share/pandoc/filters"]
type = "archive"
exact = true
url = "https://github.com/pandoc/lua-filters/releases/download/v2021-11-05/lua-filters.tar.gz"
stripComponents = 2

[".local/share/fcitx5/rime"]
type = "git-repo"
url = "https://github.com/black-desk/rime-ice"
refreshPeriod = "24h"
