# neovim
[".local/bin/nvim"]
    type = "file"
    url = "https://github.com/neovim/neovim/releases/download/v0.7.0/nvim.appimage"
    executable = true
# tmux config
[".tmux.conf"]
    type = "file"
    url = "https://raw.githubusercontent.com/gpakosz/.tmux/master/.tmux.conf"
    refreshPeriod = "24h"
# latex
["texmf/tex/latex/uniontech"]
    type = "git-repo"
    url = "https://github.com/black-desk/uniontech-latex"
["workspace/source/udoc"]
    type = "git-repo"
    url = "https://github.com/black-desk/udoc"
# note
["workspace/note"]
    type = "git-repo"
    url = "https://github.com/black-desk/Note"
["workspace/source/posts"]
    type = "git-repo"
    url = "https://github.com/black-desk/posts"
["workspace/source/pandoc-include.lua"]
    type = "git-repo"
    url = "https://github.com/black-desk/pandoc-include.lua"
# my projects
["workspace/source/fcitx5-ui.nvim"]
    type = "git-repo"
    url = "https://github.com/black-desk/fcitx5-ui.nvim"
["workspace/source/tree-sitter-commonmark"]
    type = "git-repo"
    url = "https://github.com/black-desk/tree-sitter-commonmark"
["workspace/source/mahjim"]
    type = "git-repo"
    url = "https://github.com/black-desk/mahjim"
["workspace/aur/overgrive"]
    type = "git-repo"
    url = "ssh://aur@aur.archlinux.org/overgrive.git"
# my fork
["workspace/source/ccls"]
    type = "git-repo"
    url = "https://github.com/black-desk/ccls"
["workspace/refer/cmark-gfm"]
    type = "git-repo"
    url = "https://github.com/github/cmark-gfm"
["workspace/source/nvim-lspconfig"]
    type = "git-repo"
    url = "https://github.com/black-desk/nvim-lspconfig"
# refer
["workspace/refer/linux-pam"]
    type = "git-repo"
    url = "https://github.com/linux-pam/linux-pam"
["workspace/refer/cmark"]
    type = "git-repo"
    url = "https://github.com/commonmark/cmark"
["workspace/refer/dbus"]
    type = "git-repo"
    url = "https://github.com/freedesktop/dbus"
["workspace/refer/neovim"]
    type = "git-repo"
    url = "https://github.com/neovim/neovim"
["workspace/refer/pandoc"]
    type = "git-repo"
    url = "https://github.com/jgm/pandoc"
["workspace/refer/pandoc-types"]
    type = "git-repo"
    url = "https://github.com/jgm/pandoc-types"
["workspace/refer/qtctreator"]
    type = "git-repo"
    url = "https://github.com/qt-creator/qt-creator"
["workspace/refer/golang-tools"]
    type = "git-repo"
    url = "https://github.com/golang/tools"
# others
["workspace/uniontech/dde-go"]
    type = "git-repo"
    url = "https://github.com/black-desk/dde-go"
