#!/usr/bin/env sh

# This file will be sourced by both .bashrc and .zshrc

if locale -a | grep --quiet zh_CN.UTF-8; then
	export LANG=zh_CN.UTF-8
	export LANGUAGE=zh_CN
fi

if locale -a | grep --quiet en_US; then
	export LANGAUGE="$LANGUAGE${LANGUAGE+:}en_US"
fi

function check() {
	command -v "$1" &>/dev/null
}

function prepend_path() {
	case ":${PATH}:" in
	    *:"$1":*)
		;;
	    *)
		export PATH="$1:$PATH"
		;;
	esac
}

if [[ -n $WSL_DISTRO_NAME ]]; then
	OLD_PATH="$PATH"
	NEW_PATH=""
	IFS=':'
	for p in $OLD_PATH; do
		if [[ "$p" == /mnt/c* ]]; then
			continue
		fi

		if [ -z "$NEW_PATH" ]; then
			NEW_PATH="$p"
			continue
		fi

		NEW_PATH="$NEW_PATH:$p"
	done
	PATH="$HOME/.local/lib/wsl/bin:$NEW_PATH"
fi


prepend_path "/sbin"
prepend_path "/bin"
prepend_path "/usr/sbin"
prepend_path "/usr/bin"
prepend_path "/usr/local/sbin"
prepend_path "/usr/local/bin"
prepend_path "/opt/sbin"
prepend_path "/opt/bin"
prepend_path "/opt/local/sbin" # macports
prepend_path "/opt/local/bin" # macports
prepend_path "$HOME/.local/bin"

if check ruby; then
	export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
	prepend_path "$GEM_HOME/bin"
fi

if [ -z "$GOENV_ROOT" ] && [ -x "$HOME/.goenv/bin/goenv" ]; then
	export GOENV_ROOT="$HOME/.goenv"
	prepend_path "$GOENV_ROOT/bin"
fi

if check goenv; then
	eval "$(goenv init -)"
fi

if check go; then
	prepend_path "$(go env GOPATH)/bin"
fi

if [ -f "$HOME/.cargo/env" ]; then
	. "$HOME/.cargo/env"
fi

if [ -f "$HOME/.xmake/profile" ]; then
	. "$HOME/.xmake/profile"
fi

if [ -z "$N_PREFIX" ] && [ -x "$HOME/.n/bin/n" ]; then
	export N_PREFIX="$HOME/.n"
	prepend_path "$N_PREFIX/bin"
fi

if check less; then
	export PAGER=less
fi

if check gpg; then
	GPG_TTY="$(tty)"
	export GPG_TTY
fi

if check gpgconf; then
	SSH_AUTH_SOCK="$(gpgconf --list-dirs agent-ssh-socket)"
	export SSH_AUTH_SOCK
fi

if check gdb; then
	if grep Debian --quiet /etc/os-release; then
		export DEBUGINFOD_URLS="https://debuginfod.debian.net"
	fi

	if grep Ubuntu --quiet /etc/os-release; then
		export DEBUGINFOD_URLS="https://debuginfod.ubuntu.com"
	fi
fi

if check cmake; then
	export CPM_SOURCE_CACHE="$HOME/.cache/CPM"
fi

if check vim; then
        export VISUAL=vim
        export EDITOR=vim
fi

if check nvim; then
        export VISUAL=nvim
        export EDITOR=nvim
fi

unset check
unset prepend_path

export PINYIN_COMP_MODE="ShuangpinXiaohe"
