#!/usr/bin/env zsh
export my_dotfile_dir="$HOME/.dotfile"
export my_tools_dir="$HOME/.tools"

export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN:en_US

export VISUAL=nvim;
export EDITOR=nvim;
export PAGER="less -r";

export PATH="$HOME/Go/bin:$PATH"

export PATH=$PATH:~/.local/bin

export PATH="$my_tools_dir/bin:$PATH"
export PATH="$my_tools_dir/bin/uniontech:$PATH"

export HISTFILE="$HOME/.zsh_history"
export SAVEHIST=5000
export HISTSIZE=5000

if [[ `type Xorg` ]] ; then
  export _GUI_="True"
fi
