#!/usr/bin/env zsh

if [[ "$TERM_PROGRAM" != "WezTerm" ]] && [[ -n "$PS1" ]] &&
        [[ -z "$TMUX" ]] && [[ -n "$SSH_CONNECTION" ]]; then
        tmux attach-session -t ssh || tmux new-session -s ssh
        exit
fi


[[ $(tty) == \/dev\/tty[0-6]* ]] &&
        fbterm -s 18 -n "MesloLGS NF" &> ~/.cache/fbterm-log.txt &&
        exit

if [[ ! -f $HOME/.zinit/bin/zinit.zsh ]]; then
    print -P "%F{33}▓▒░ %F{220}Installing %F{33}DHARMA%F{220} Initiative Plugin Manager (%F{33}zdharma/zinit%F{220})…%f"
    command mkdir -p "$HOME/.zinit" && command chmod g-rwX "$HOME/.zinit"
    command git clone https://github.com/zdharma-continuum/zinit "$HOME/.zinit/bin" && \
        print -P "%F{33}▓▒░ %F{34}Installation successful.%f%b" || \
        print -P "%F{160}▓▒░ The clone has failed.%f%b"
fi
source "$HOME/.zinit/bin/zinit.zsh"
autoload -Uz _zinit
(( ${+_comps} )) && _comps[zinit]=_zinit

zinit wait lucid light-mode for \
atinit"zicompinit; zicdreplay" \
    zdharma-continuum/fast-syntax-highlighting \
atload"_zsh_autosuggest_start" \
    zsh-users/zsh-autosuggestions \
blockf atpull'zinit creinstall -q .' \
    zsh-users/zsh-completions \
atload"[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh && compdef dial=ssh" \
    agkozak/zsh-z \
    esc/conda-zsh-completion \

zinit ice depth=1 atinit"[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh"
zinit light romkatv/powerlevel10k

bindkey -v

bindkey -s '^g' "lazygit^M"
bindkey -s '^h' "^[[D"
bindkey -s '^j' "^[[B"
bindkey -s '^k' "^[[A"
bindkey -s '^l' "^[[C"

alias sudo="sudo "

alias ls="ls --color"
alias la="ls -la"
alias ra="ranger"

alias pkg_auto_remove="sudo pacman -Rcns \$(pacman -Qdtq)"
alias pkg_source="asp export"
alias yay="CC= CXX= CMAKE_C_COMPILER= CMAKE_CXX_COMPILER= CMAKE_GENERATOR= CMAKE_C_FLAGS= CMAKE_CXX_FLAGS= yay"

alias gst="git status"
alias lazygit="LANG=en_US lazygit"

alias cfg="chezmoi"

alias clang-format-all="find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\|h\)' -exec clang-format -style=file -i {} \;"
alias cmake-buildj="cmake --build build -j $(($(nproc) - 1))"
alias getcpm="wget -O CPM.cmake https://github.com/cpm-cmake/CPM.cmake/releases/latest/download/CPM.cmake"

setopt autopushd pushdsilent pushdtohome
setopt pushdignoredups # Remove duplicate entries
setopt pushdminus # This reverts the +/- operators.

alias bk="popd"

alias R='cd "$(realpath "`pwd`")"'
alias s="dirs -v"

export GPG_TTY=$(tty)

R
