#!/usr/bin/env zsh
export LANG=zh_CN.UTF-8
export LANGUAGE=zh_CN:en_US

export VISUAL=nvim;
export EDITOR=nvim;
export PAGER="less -r";

export PATH=$HOME/Go/bin:$PATH

export PATH=$HOME/.ghcup/bin:$PATH

export PATH=$HOME/.local/bin:$PATH

export HISTFILE="$HOME/.zsh_history"
export SAVEHIST=5000
export HISTSIZE=5000

export CMAKE_EXPORT_COMPILE_COMMANDS=1

if [[ `type Xorg` ]] ; then
  export _GUI_="True"
fi
